baseURL: https://microsoft.github.io/powercat-automation-kit/
languageCode: en-us
title: Automation Kit for Power Platform
theme: hugo-fresh
publishDir: ../docs
relativeURLs: false
canonifyURLS: true

# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  image: https://microsoft.github.io/powercat-automation-kit/images/logos/automation-kit.png
  imagealt: Automation Kit Logo

  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  
  description: Automation Kit for Power Platform starter site. Summary of Automation Kit value story, learning content and customer stories.
  # Preloader ensures images are loaded before displaying to the user. If you don't want it uncomment to set it to false
  # preloader: false
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/automation-kit.svg
    link: /
    # Default width/height. Uncomment if you need to change
    # width: 112
    # height: 28
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Automation Kit for Power Platform
    # Hero subtitle (optional)
    subtitle: Accelerates the use and support of Power Automate for desktop for automation projects
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: /get-started
    # Hero image (from static/images/___)
    image: illustrations/worker-public-preview.svg
    # Footer logos (from static/images/logos/clients/___.svg)
    clientlogos:
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Customer Stories
    url: /customer-stories
  - title: Learn
    url: https://aka.ms/automation-kit-learn
  - title: Office Hours
    url: /office-hours
    button: true
  section1:
    tiles:
    - title: Join the Community
      subtitle: Join our office hours to see new features, discuss roadmap and "Ask Me Anything" question and answers
      icon: meeting
      buttonText: Office Hours
      url: office-hours
    - title: Make a contribution
      icon: community
      buttonText: Read More
      url: contribution
    - title: Frequently Asked Questions
      icon: question
      buttonText: Read More
      url: frequently-asked-questions
  section2:
    title: Manage, Govern and Scale
    subtitle: Enable organizations to manage, govern and scale automation platform adoption based on industryâ€™s best practices
    features:
    - title: Near-real time ROI/ SLA
      text: Short- and long-term analytics to drive towards your business goals
      icon: roi
    - title: Tools for all users
      text: Makers(citizen & pro), Automation CoE team, Exec sponsors
      icon: users
    - title: End-end automation lifecycle
      text: Tools to automate & manage all aspects of Hyper-automation scenarios including ALM, templates to drive consistency
      icon: automation
    - title: Enterprise readiness
      text: Secure, govern, audit and monitor your Automation deployment
      icon: enterprise
  section3:
    title: Monitor Value
    subtitle: Project Definition to SLA & ROI based near-real-time reporting 
    image: illustrations/end-to-end.png
    buttonText: Learn More
    buttonLink: "https://learn.microsoft.com/power-automate/guidance/automation-kit/overview/automation-coe-strategy#automation-lifecycle"
  footer:
    # Logo (from /images/logos/___)
    logo: automation-kit.svg
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/microsoft/powercat-automation-kit
      # Icons are from Font Awesome
      icon: github
    bulmalogo: false
    quicklinks:
      column1:
        title: "Product"
        links:
        - text: FAQ
          link: /frequently-asked-questions
        - text: Support
          link: /support
        - text: Office Hours
          link: /office-hours
        - text: Discover features
          link: https://aka.ms/automation-kit-learn
        - text: Issues
          link: https://aka.ms/ak4pp-issues
        - text: Milestones
          link: https://github.com/microsoft/powercat-automation-kit/milestones?status=open
        - text: Releases
          link: https://github.com/microsoft/powercat-automation-kit/releases
      column2:
        title: "Learn"
        links:
        - text: Get started
          link: https://learn.microsoft.com/power-automate/guidance/automation-kit/setup/prerequisites
        - text: Configure the Automation Kit
          link: https://learn.microsoft.com/power-automate/guidance/automation-kit/configure-automation-kit
        - text: Use the Automation Kit
          link: https://learn.microsoft.com/power-automate/guidance/automation-kit/use-automation-kit
      column3:
        title: "Blog"
        links:
        - text: Public Preview
          link: https://aka.ms/automation-kit-blog
        - text: Cineplex Customer Story
          link: https://powerautomate.microsoft.com/blog/cineplex-digital-transformation-with-power-automate-rpa-led-by-citizen-developers/
